export interface EboxCategory {
  id: string
  name: string
  iconName: string
  count: number
  description: string
}

export interface EboxItem {
  id: string
  title: string
  category: string
  fileType: 'pdf' | 'xlsx' | 'docx' | 'png' | 'zip' | 'csv' | 'json'
  size: string
  updatedAt: string
  uploadedBy: string
  status: 'Verified' | 'Pending Review' | 'Archived' | 'Required Action'
  tags: string[]
  downloadUrl?: string
  description?: string
  securityLevel: 'Public' | 'Encrypted' | 'Restricted'
}

export const EBOX_CATEGORIES: EboxCategory[] = [
  {
    id: 'all',
    name: 'All Vault Items',
    iconName: 'Folder',
    count: 14,
    description: 'Master view of all uploaded repository artifacts and vault assets.',
  },
  {
    id: 'capital-docs',
    name: 'Capital & Credit Lines',
    iconName: 'Wallet',
    count: 4,
    description: 'Loan agreements, term sheets, UCC filings, and facility draw proofs.',
  },
  {
    id: 'financial-audits',
    name: 'Financial Audits',
    iconName: 'FileCheck',
    count: 3,
    description: 'Certified P&L statements, balance sheet reconciliations, and tax returns.',
  },
  {
    id: 'cfo-reports',
    name: 'CFO Strategic Reports',
    iconName: 'TrendingUp',
    count: 4,
    description: '13-week cash flow forecasts, unit economics, and board decks.',
  },
  {
    id: 'legal-compliance',
    name: 'Legal & Compliance',
    iconName: 'ShieldCheck',
    count: 3,
    description: 'Operating agreements, corporate governance, and KYB verifications.',
  },
]

export const EBOX_ITEMS: EboxItem[] = [
  {
    id: 'ebx_001',
    title: 'Q3_2026_Audited_Financial_Package.pdf',
    category: 'financial-audits',
    fileType: 'pdf',
    size: '4.8 MB',
    updatedAt: '2026-10-04',
    uploadedBy: 'Marcus Vance (CEO)',
    status: 'Verified',
    tags: ['Audited', 'Q3 Financials', 'Tax Compliance'],
    description: 'Complete quarterly audited financials reviewed by Deloitte & Touche LLP.',
    securityLevel: 'Encrypted',
  },
  {
    id: 'ebx_002',
    title: 'Apex_Revolving_Line_Agreement_TermSheet.pdf',
    category: 'capital-docs',
    fileType: 'pdf',
    size: '12.4 MB',
    updatedAt: '2026-09-28',
    uploadedBy: 'B4B Underwriting Desk',
    status: 'Verified',
    tags: ['Facility', '$850k Line', 'Binding Terms'],
    description: 'Official master line credit facility documentation signed by all guarantors.',
    securityLevel: 'Restricted',
  },
  {
    id: 'ebx_003',
    title: 'CashFlow_Forecast_Model_13Week.xlsx',
    category: 'cfo-reports',
    fileType: 'xlsx',
    size: '2.1 MB',
    updatedAt: '2026-10-06',
    uploadedBy: 'David Ross (Fractional CFO)',
    status: 'Verified',
    tags: ['13-Week Treasury', 'Rolling Model', 'CFO Approved'],
    description: 'Dynamic 13-week rolling cash flow model incorporating Q4 revenue acceleration.',
    securityLevel: 'Encrypted',
  },
  {
    id: 'ebx_004',
    title: '2025_IRS_Tax_Return_Form_1120S.pdf',
    category: 'financial-audits',
    fileType: 'pdf',
    size: '3.6 MB',
    updatedAt: '2026-08-15',
    uploadedBy: 'Marcus Vance (CEO)',
    status: 'Verified',
    tags: ['IRS', '1120S', 'Tax Return'],
    description: 'Filed Federal S-Corporation Tax Return with schedule K-1 attachments.',
    securityLevel: 'Encrypted',
  },
  {
    id: 'ebx_005',
    title: 'UCC1_Financing_Statement_Disbursement.pdf',
    category: 'capital-docs',
    fileType: 'pdf',
    size: '890 KB',
    updatedAt: '2026-09-29',
    uploadedBy: 'Legal Compliance Desk',
    status: 'Verified',
    tags: ['UCC-1', 'Lien Search', 'Secured'],
    description: 'State Secretary filing confirming security position on general intangibles.',
    securityLevel: 'Public',
  },
  {
    id: 'ebx_006',
    title: 'Unit_Economics_Customer_Cohort_Analysis.xlsx',
    category: 'cfo-reports',
    fileType: 'xlsx',
    size: '5.2 MB',
    updatedAt: '2026-10-01',
    uploadedBy: 'David Ross (Fractional CFO)',
    status: 'Pending Review',
    tags: ['Cohort LTV', 'CAC Ratio', 'Retention'],
    description: 'Detailed analysis of gross margins by freight route and customer retention cohort.',
    securityLevel: 'Encrypted',
  },
  {
    id: 'ebx_007',
    title: 'Articles_of_Organization_OperatingAgreement.pdf',
    category: 'legal-compliance',
    fileType: 'pdf',
    size: '1.8 MB',
    updatedAt: '2026-07-10',
    uploadedBy: 'Marcus Vance (CEO)',
    status: 'Verified',
    tags: ['Corporate', 'Delaware LLC', 'Governance'],
    description: 'Delaware corporate charter and multi-member operating agreement.',
    securityLevel: 'Restricted',
  },
  {
    id: 'ebx_008',
    title: 'Equipment_Lease_Schedule_Fleet_2026.docx',
    category: 'capital-docs',
    fileType: 'docx',
    size: '640 KB',
    updatedAt: '2026-09-12',
    uploadedBy: 'Ops Department',
    status: 'Required Action',
    tags: ['Fleet Lease', 'Asset Collateral'],
    description: 'Schedule A listing active tractor-trailer VINs and lease payment maturities.',
    securityLevel: 'Public',
  },
  {
    id: 'ebx_009',
    title: 'Board_Deck_Q4_Capital_Expansion.pdf',
    category: 'cfo-reports',
    fileType: 'pdf',
    size: '18.9 MB',
    updatedAt: '2026-10-05',
    uploadedBy: 'David Ross (Fractional CFO)',
    status: 'Verified',
    tags: ['Board Deck', 'Strategy', 'Q4 Growth'],
    description: 'Executive presentation deck for upcoming board strategy meeting.',
    securityLevel: 'Restricted',
  },
  {
    id: 'ebx_010',
    title: 'Bank_Statement_Reconciliation_Sept2026.pdf',
    category: 'financial-audits',
    fileType: 'pdf',
    size: '2.4 MB',
    updatedAt: '2026-10-02',
    uploadedBy: 'Marcus Vance (CEO)',
    status: 'Verified',
    tags: ['Bank Statement', 'Chase Business'],
    description: 'Verified monthly bank statement and transaction ledger.',
    securityLevel: 'Encrypted',
  },
  {
    id: 'ebx_011',
    title: 'KYB_Corporate_Beneficial_Ownership_Form.pdf',
    category: 'legal-compliance',
    fileType: 'pdf',
    size: '720 KB',
    updatedAt: '2026-08-20',
    uploadedBy: 'Compliance Desk',
    status: 'Verified',
    tags: ['FinCEN', 'BOI', 'Compliance'],
    description: 'FinCEN Beneficial Ownership Information filing receipt.',
    securityLevel: 'Restricted',
  },
  {
    id: 'ebx_012',
    title: 'Insurance_Certificate_COI_GeneralLiability.pdf',
    category: 'legal-compliance',
    fileType: 'pdf',
    size: '1.1 MB',
    updatedAt: '2026-09-01',
    uploadedBy: 'Risk Desk',
    status: 'Verified',
    tags: ['Insurance', 'COI', '$5M Umbrella'],
    description: 'Certificate of Insurance showing B4B Capital as additional loss payee.',
    securityLevel: 'Public',
  },
  {
    id: 'ebx_013',
    title: 'Vendor_Payables_Aging_Summary.csv',
    category: 'cfo-reports',
    fileType: 'csv',
    size: '410 KB',
    updatedAt: '2026-10-07',
    uploadedBy: 'David Ross (Fractional CFO)',
    status: 'Verified',
    tags: ['Accounts Payable', '30-60-90 Aging'],
    description: 'Raw accounts payable breakdown by vendor payment term.',
    securityLevel: 'Encrypted',
  },
  {
    id: 'ebx_014',
    title: 'Disbursement_Wire_Receipt_Draw_04.pdf',
    category: 'capital-docs',
    fileType: 'pdf',
    size: '350 KB',
    updatedAt: '2026-10-03',
    uploadedBy: 'B4B Treasury Desk',
    status: 'Verified',
    tags: ['FedWire', '$50,000 Disbursement'],
    description: 'FedWire transfer confirmation for capital draw #04.',
    securityLevel: 'Restricted',
  },
]
