/**
 * B4B AMERICA — VERIFIED JOBS BOARD DATA
 * 
 * Sourced directly from official client document:
 * "10_  B4B Jobs - B4B Solutions.docx"
 * 
 * ALL DEMO JOBS ARE CLEARLY LABELED WITH isDemo: true AND "DEMO DATA" BADGE
 * SO THEY CAN BE REMOVED/PURGED PRIOR TO THE SOFT LAUNCH.
 */

export interface Job {
  id: string
  title: string
  company: string
  category: string
  state: string
  city: string
  salary: string
  salaryMin: number
  salaryMax: number
  jobType: 'Full-time' | 'Part-time' | 'Contract' | 'Gig' | 'Commission' | 'Internship'
  description: string
  requirements?: string[]
  contactEmail: string
  status: 'approved' | 'pending' | 'rejected'
  rejectionReason?: string
  isDemo: boolean
  createdAt: string
  featured?: boolean
}

export interface JobFilters {
  keyword?: string
  category?: string
  state?: string
  city?: string
  minSalary?: number
  maxSalary?: number
  jobTypes?: string[]
  sortBy?: 'newest' | 'salary_high' | 'salary_low' | 'relevance'
  page?: number
  limit?: number
}

// Exact lists from "10_  B4B Jobs - B4B Solutions.docx"
export const POPULAR_SEARCHES_CLIENT = [
  'Administrative',
  'Business-to-Business (B2B) Sales',
  'Business-to-Consumer (B2C) Sales',
  'Customer Service',
  'Education',
  'Healthcare',
  'Insurance Sales',
  'Internships',
  'Marketing',
  'Medical Sales',
  'Part-time',
  'Sales',
  'Software Sales',
  'Technology',
  'Warehouse',
  'Web Design',
  'Work from home',
]

export const JOB_CATEGORIES_CLIENT = [
  'B2B Sales',
  'B2C Sales',
  'Software Sales',
  'Insurance Sales',
  'Medical Device Sales',
  'Real Estate & Property Management',
  'Technology (SaaS)',
  'AI/ML',
  'Data Analytics',
  'Healthcare/Pharmaceuticals',
  'Finance & Insurance',
  'Account Executives',
  'Customer Service',
  'Marketing / PR / Advertising',
  'Web / Info Design',
  'Skilled Trade / Craft',
  'Construction Managers',
  'Food / Beverage / Hospitality',
  'Logistics Broker',
  'Admin / Office',
]

export const JOB_LOCATIONS_CLIENT = [
  { city: 'NYC', state: 'NY' },
  { city: 'Atlanta', state: 'GA' },
  { city: 'Austin', state: 'TX' },
  { city: 'Boston', state: 'MA' },
  { city: 'Chicago', state: 'IL' },
  { city: 'Dallas', state: 'TX' },
  { city: 'Denver', state: 'CO' },
  { city: 'Detroit', state: 'MI' },
  { city: 'Houston', state: 'TX' },
  { city: 'Indianapolis', state: 'IN' },
  { city: 'Las Vegas', state: 'NV' },
  { city: 'Los Angeles', state: 'CA' },
  { city: 'Miami', state: 'FL' },
  { city: 'Nashville', state: 'TN' },
  { city: 'Orlando', state: 'FL' },
  { city: 'Philadelphia', state: 'PA' },
  { city: 'Phoenix', state: 'AZ' },
  { city: 'Portland', state: 'OR' },
  { city: 'Raleigh', state: 'NC' },
  { city: 'San Antonio', state: 'TX' },
  { city: 'San Diego', state: 'CA' },
  { city: 'San Francisco', state: 'CA' },
  { city: 'Seattle', state: 'WA' },
  { city: 'Washington', state: 'DC' },
]

export const SALARY_RANGES_CLIENT = [
  { label: '50k - 75k + annually', min: 50000, max: 75000 },
  { label: '100k - 225k annually', min: 100000, max: 225000 },
  { label: '225k+ - 350k annually', min: 225000, max: 350000 },
  { label: '350k + annually', min: 350000, max: 1000000 },
]

export const GIGS_CLIENT = [
  '150k + gigs',
  '250k + gigs',
  'Automotive',
  'Canvassing / Petition Gigs',
  'Computer',
  'Cleaning',
  'Crew',
  'Domestic',
  'Event',
  'Handyman',
  'Influencer',
  'Labor',
  'Podcast',
  'Promoter',
  'Talent',
  'Web Design',
  'Writing',
  'Resumes',
]

/**
 * 30 Initial Demo Jobs
 * Covering client sectors and major American territories.
 * All marked with isDemo: true and demo badges.
 */
export const INITIAL_DEMO_JOBS: Job[] = [
  {
    id: 'demo-job-01',
    title: 'Senior Enterprise B2B Account Executive',
    company: 'Apex Merchant Systems',
    category: 'B2B Sales',
    state: 'NY',
    city: 'NYC',
    salary: '$110,000 - $145,000 annually',
    salaryMin: 110000,
    salaryMax: 145000,
    jobType: 'Full-time',
    description: 'Lead merchant services acquisition for high-volume retail and logistics operators. Build territory pipeline and close enterprise processing agreements.',
    requirements: ['4+ years B2B sales experience', 'Proven quota achievement', 'Strong consultative negotiation'],
    contactEmail: 'careers@apexmerchants.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-01T10:00:00Z',
    featured: true,
  },
  {
    id: 'demo-job-02',
    title: 'Commercial Insurance Broker',
    company: 'Liberty Shield Risk Group',
    category: 'Insurance Sales',
    state: 'IL',
    city: 'Chicago',
    salary: '$85,000 - $120,000 + Commission',
    salaryMin: 85000,
    salaryMax: 120000,
    jobType: 'Full-time',
    description: 'Advise mid-market logistics and manufacturing firms on general liability, workers comp, and commercial umbrella policies.',
    requirements: ['Active P&C Insurance License', '2+ years commercial brokerage', 'Excellent client communication'],
    contactEmail: 'hiring@libertyshield.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-02T11:00:00Z',
    featured: true,
  },
  {
    id: 'demo-job-03',
    title: 'Senior Full-Stack Software Developer (React / Node)',
    company: 'CloudSphere Solutions',
    category: 'Technology (SaaS)',
    state: 'TX',
    city: 'Austin',
    salary: '$130,000 - $165,000 annually',
    salaryMin: 130000,
    salaryMax: 165000,
    jobType: 'Full-time',
    description: 'Design and deploy scalable web apps, REST APIs, and client dashboards for modern fintech infrastructure.',
    requirements: ['5+ years TypeScript/React/Node.js', 'Experience with PostgreSQL or MongoDB', 'Familiarity with cloud hosting'],
    contactEmail: 'devs@cloudsphere.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-02T14:30:00Z',
    featured: true,
  },
  {
    id: 'demo-job-04',
    title: 'Customer Success Manager (B2B SaaS)',
    company: 'ScaleMetric Hub',
    category: 'Customer Service',
    state: 'GA',
    city: 'Atlanta',
    salary: '$75,000 - $95,000 annually',
    salaryMin: 75000,
    salaryMax: 95000,
    jobType: 'Full-time',
    description: 'Manage onboarding, adoption, and retention for 80+ mid-sized enterprise clients using operations software.',
    requirements: ['3+ years in customer success or account management', 'Empathetic issue resolution', 'CRM software proficiency'],
    contactEmail: 'hr@scalemetric.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-03T09:15:00Z',
  },
  {
    id: 'demo-job-05',
    title: 'Freight Logistics Broker & Dispatcher',
    company: 'CrossCountry Freightlines',
    category: 'Logistics Broker',
    state: 'TX',
    city: 'Dallas',
    salary: '$65,000 - $90,000 + Bonus',
    salaryMin: 65000,
    salaryMax: 90000,
    jobType: 'Full-time',
    description: 'Coordinate freight routes, negotiate carrier spot rates, and maintain carrier relationships across southern shipping lanes.',
    requirements: ['2+ years 3PL dispatch or brokerage experience', 'TMS software knowledge', 'Strong multitasking'],
    contactEmail: 'dispatch@crosscountry.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-03T16:00:00Z',
  },
  {
    id: 'demo-job-06',
    title: 'Medical Device Sales Representative',
    company: 'BioVanguard Surgical',
    category: 'Medical Device Sales',
    state: 'MA',
    city: 'Boston',
    salary: '$140,000 - $190,000 + Commission',
    salaryMin: 140000,
    salaryMax: 190000,
    jobType: 'Full-time',
    description: 'Introduce minimally invasive surgical equipment to hospital networks, outpatient surgery centers, and regional health clinics.',
    requirements: ['Bachelor degree in Life Sciences or Business', '3+ years medical sales track record', 'Operating room protocol certified'],
    contactEmail: 'talent@biovanguard.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-04T08:00:00Z',
    featured: true,
  },
  {
    id: 'demo-job-07',
    title: 'Lead UI/UX & Web Designer',
    company: 'PixelCraft Studio',
    category: 'Web / Info Design',
    state: 'CA',
    city: 'Los Angeles',
    salary: '$95,000 - $125,000 annually',
    salaryMin: 95000,
    salaryMax: 125000,
    jobType: 'Full-time',
    description: 'Transform brand identities into responsive web experiences, landing page funnels, and corporate web platforms.',
    requirements: ['Figma expert with solid CSS/HTML comprehension', 'Portfolio of live web projects', 'Experience with conversion design'],
    contactEmail: 'hello@pixelcraft.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-04T12:00:00Z',
  },
  {
    id: 'demo-job-08',
    title: 'Commercial Construction Project Manager',
    company: 'Keystone Builders LLC',
    category: 'Construction Managers',
    state: 'CO',
    city: 'Denver',
    salary: '$105,000 - $135,000 annually',
    salaryMin: 105000,
    salaryMax: 135000,
    jobType: 'Full-time',
    description: 'Oversee ground-up commercial projects, subcontractor bidding, OSHA safety compliance, and timeline management.',
    requirements: ['OSHA 30 certification', '5+ years commercial construction PM', 'Procore experience'],
    contactEmail: 'jobs@keystonebuild.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-04T15:00:00Z',
  },
  {
    id: 'demo-job-09',
    title: 'Digital Marketing & PPC Campaign Specialist',
    company: 'Velocity Growth Media',
    category: 'Marketing / PR / Advertising',
    state: 'FL',
    city: 'Miami',
    salary: '$70,000 - $90,000 annually',
    salaryMin: 70000,
    salaryMax: 90000,
    jobType: 'Full-time',
    description: 'Manage Google Ads, Meta PPC, and local SEO campaigns for multi-location regional service businesses.',
    requirements: ['Google Ads certified', '3+ years running paid ad spend > $50k/mo', 'Data-driven analytics mindset'],
    contactEmail: 'media@velocitygrowth.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-05T09:30:00Z',
  },
  {
    id: 'demo-job-10',
    title: 'Senior AI/ML Computer Vision Engineer',
    company: 'CognitiveWave Labs',
    category: 'AI/ML',
    state: 'CA',
    city: 'San Francisco',
    salary: '$180,000 - $240,000 annually',
    salaryMin: 180000,
    salaryMax: 240000,
    jobType: 'Full-time',
    description: 'Develop automated image recognition and document OCR models for commercial processing verification systems.',
    requirements: ['MS/PhD in Computer Science or Math', 'PyTorch / TensorFlow proficiency', 'Production deployment experience'],
    contactEmail: 'recruiting@cognitivewave.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-05T14:00:00Z',
    featured: true,
  },
  {
    id: 'demo-job-11',
    title: 'Licensed Real Estate Sales Consultant',
    company: 'Metropolitan Commercial Realty',
    category: 'Real Estate & Property Management',
    state: 'AZ',
    city: 'Phoenix',
    salary: '$80,000 - $160,000 (Commission based)',
    salaryMin: 80000,
    salaryMax: 160000,
    jobType: 'Commission',
    description: 'Represent buyers and tenants in commercial property leasing, industrial flex spaces, and retail storefront transactions.',
    requirements: ['Active Arizona Real Estate License', 'Proven sales negotiation skills', 'Local territory network'],
    contactEmail: 'realty@metropolitangroup.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-05T16:45:00Z',
  },
  {
    id: 'demo-job-12',
    title: 'Senior Financial Analyst & Modeler',
    company: 'Capital Ridge Advisory',
    category: 'Finance & Insurance',
    state: 'NC',
    city: 'Charlotte',
    salary: '$95,000 - $125,000 annually',
    salaryMin: 95000,
    salaryMax: 125000,
    jobType: 'Full-time',
    description: 'Construct 3-statement models, DCF valuations, and debt service coverage analysis for mid-market loan syndications.',
    requirements: ['CFA or advanced finance degree', 'Advanced Excel / financial modeling', '2+ years corporate banking or advisory'],
    contactEmail: 'advisory@capitalridge.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-06T09:00:00Z',
  },
  {
    id: 'demo-job-13',
    title: 'Hospitality General Operations Manager',
    company: 'The Grandview Bistro Group',
    category: 'Food / Beverage / Hospitality',
    state: 'WA',
    city: 'Seattle',
    salary: '$75,000 - $95,000 annually',
    salaryMin: 75000,
    salaryMax: 95000,
    jobType: 'Full-time',
    description: 'Lead day-to-day front and back of house operations, manage vendor food costs, and enforce premier hospitality standards.',
    requirements: ['ServSafe Manager Certification', '4+ years high-volume restaurant management', 'P&L budget accountability'],
    contactEmail: 'ops@grandviewbistro.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-06T11:30:00Z',
  },
  {
    id: 'demo-job-14',
    title: 'HVAC Master Technician & Field Supervisor',
    company: 'Reliant Climate Systems',
    category: 'Skilled Trade / Craft',
    state: 'TX',
    city: 'Houston',
    salary: '$70,000 - $95,000 + Overtime',
    salaryMin: 70000,
    salaryMax: 95000,
    jobType: 'Full-time',
    description: 'Diagnose, repair, and install commercial roof-top units and chillers. Mentor junior apprentice technicians.',
    requirements: ['EPA Universal Certification', '5+ years commercial HVAC', 'Clean driving record'],
    contactEmail: 'service@reliantclimate.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-06T13:45:00Z',
  },
  {
    id: 'demo-job-15',
    title: 'Executive Assistant & Office Administrator',
    company: 'Summit Legal Partners',
    category: 'Admin / Office',
    state: 'DC',
    city: 'Washington',
    salary: '$60,000 - $78,000 annually',
    salaryMin: 60000,
    salaryMax: 78000,
    jobType: 'Full-time',
    description: 'Provide high-level calendar management, client intake correspondence, and administrative support to senior corporate partners.',
    requirements: ['3+ years executive assistant experience', 'High discretion and confidentiality', 'Mastery of MS Office Suite'],
    contactEmail: 'admin@summitlegal.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-06T15:20:00Z',
  },
  {
    id: 'demo-job-16',
    title: 'Freelance Mobile Web Optimization Expert',
    company: 'SpeedCraft Studios',
    category: 'Web / Info Design',
    state: 'NY',
    city: 'NYC',
    salary: '$60 - $85 / hr (Gig Contract)',
    salaryMin: 60000,
    salaryMax: 95000,
    jobType: 'Gig',
    description: 'Audit and optimize Core Web Vitals, page speed, and interactive mobile UI for e-commerce stores.',
    requirements: ['Deep knowledge of Lighthouse and responsive CSS', 'Ability to turnaround 48-hr performance audits'],
    contactEmail: 'gigs@speedcraft.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-07T08:10:00Z',
  },
  {
    id: 'demo-job-17',
    title: 'Outside Sales B2B Territory Consultant',
    company: 'Empire Point POS Solutions',
    category: 'B2B Sales',
    state: 'PA',
    city: 'Philadelphia',
    salary: '$75,000 base + Uncapped Commission ($130k+ OTE)',
    salaryMin: 75000,
    salaryMax: 130000,
    jobType: 'Full-time',
    description: 'Visit local storefronts and dining establishments to present modern smart payment terminals with lower interchange rates.',
    requirements: ['Energetic face-to-face prospecting', 'Valid driver license and vehicle', 'B2B field sales background'],
    contactEmail: 'territory@empirepoint.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-07T10:00:00Z',
  },
  {
    id: 'demo-job-18',
    title: 'Direct Sales Loan Agent (Working Capital)',
    company: 'Capital First Lending',
    category: 'Finance & Insurance',
    state: 'TN',
    city: 'Nashville',
    salary: '$70,000 - $110,000 annually',
    salaryMin: 70000,
    salaryMax: 110000,
    jobType: 'Full-time',
    description: 'Review merchant funding applications, verify bank statements, and match small business borrowers with term facilities.',
    requirements: ['2+ years alternative lending or banking', 'Understanding of cash flow and debt service ratios'],
    contactEmail: 'agents@capitalfirst.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-07T12:00:00Z',
  },
  {
    id: 'demo-job-19',
    title: 'Event Video & Podcast Production Assistant',
    company: 'Vanguard Media Group',
    category: 'Marketing / PR / Advertising',
    state: 'NV',
    city: 'Las Vegas',
    salary: '$28 - $38 / hr (Part-time Gigs)',
    salaryMin: 45000,
    salaryMax: 65000,
    jobType: 'Gig',
    description: 'Assist with multi-camera live switching, audio recording, and podcast lighting setup during convention conferences.',
    requirements: ['Experience with Blackmagic or Sony cameras', 'Clean audio recording skills', 'Weekend availability'],
    contactEmail: 'events@vanguardmedia.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-07T14:30:00Z',
  },
  {
    id: 'demo-job-20',
    title: 'Biotech Lab Data Analytics Associate',
    company: 'Genesis Genomic Systems',
    category: 'Data Analytics',
    state: 'CA',
    city: 'San Diego',
    salary: '$88,000 - $115,000 annually',
    salaryMin: 88000,
    salaryMax: 115000,
    jobType: 'Full-time',
    description: 'Clean, normalize, and visualize clinical test outcome datasets using Python, SQL, and Tableau dashboards.',
    requirements: ['BS in Data Science, Bioengineering or Statistics', 'Proficiency in Python (pandas, numpy) and SQL', 'Attention to clinical accuracy'],
    contactEmail: 'analytics@genesisgenomics.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-07T16:00:00Z',
  },
  {
    id: 'demo-job-21',
    title: 'Cybersecurity Threat Detection Analyst',
    company: 'IronClad Cyber Defense',
    category: 'Technology (SaaS)',
    state: 'MD',
    city: 'Baltimore',
    salary: '$105,000 - $135,000 annually',
    salaryMin: 105000,
    salaryMax: 135000,
    jobType: 'Full-time',
    description: 'Monitor enterprise SIEM consoles, investigate endpoint security alerts, and execute incident containment procedures.',
    requirements: ['CompTIA Security+ or CISSP', '2+ years SOC analyst experience', 'Familiarity with Wireshark and Splunk'],
    contactEmail: 'security@ironcladdefense.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-08T09:00:00Z',
  },
  {
    id: 'demo-job-22',
    title: 'Remote Medical B2C Client Coordinator',
    company: 'TeleHealth Connect USA',
    category: 'Customer Service',
    state: 'FL',
    city: 'Orlando',
    salary: '$48,000 - $62,000 annually',
    salaryMin: 48000,
    salaryMax: 62000,
    jobType: 'Full-time',
    description: 'Answer patient inquiries, verify telemedicine insurance eligibility, and schedule specialist consultations.',
    requirements: ['HIPAA compliance certification', 'Previous medical front desk or billing intake', 'Friendly bilingual phone presence'],
    contactEmail: 'telehealth@connectusa.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-08T11:15:00Z',
  },
  {
    id: 'demo-job-23',
    title: 'Part-Time Warehouse Logistics Clerk',
    company: 'Midwest Fulfillment Hub',
    category: 'Admin / Office',
    state: 'IN',
    city: 'Indianapolis',
    salary: '$22 - $26 / hr (20 hrs/week)',
    salaryMin: 32000,
    salaryMax: 45000,
    jobType: 'Part-time',
    description: 'Process incoming shipping manifests, inspect bill of ladings, and organize inventory bin records.',
    requirements: ['Forklift certification a plus', 'Detail-oriented inventory tracking', 'Reliable morning availability'],
    contactEmail: 'jobs@midwestfulfillment.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-08T13:40:00Z',
  },
  {
    id: 'demo-job-24',
    title: 'Vice President of Institutional Sales',
    company: 'Horizon National Capital',
    category: 'B2B Sales',
    state: 'NY',
    city: 'NYC',
    salary: '$225,000 - $310,000 + Equity',
    salaryMin: 225000,
    salaryMax: 310000,
    jobType: 'Full-time',
    description: 'Direct national institutional distribution, lead 15 regional sales directors, and structure syndication relationships with family offices.',
    requirements: ['10+ years executive sales leadership', 'Track record of $50M+ annual transaction volume', 'Outstanding executive presence'],
    contactEmail: 'exec@horizoncapital.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-08T15:00:00Z',
    featured: true,
  },
  {
    id: 'demo-job-25',
    title: 'Freelance Brand Identity & Logo Designer',
    company: 'Studio Vanguard',
    category: 'Web / Info Design',
    state: 'OR',
    city: 'Portland',
    salary: '$3,500 - $6,500 per client kit (Gig)',
    salaryMin: 55000,
    salaryMax: 85000,
    jobType: 'Gig',
    description: 'Create complete corporate brand packages including vector logos, typography guidelines, and apparel print templates.',
    requirements: ['Expert Adobe Illustrator and InDesign', 'Strong typography and packaging portfolio'],
    contactEmail: 'design@studiovanguard.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-08T16:30:00Z',
  },
  {
    id: 'demo-job-26',
    title: 'Commercial HVAC Field Installation Apprentice',
    company: 'Metro Air Dynamics',
    category: 'Skilled Trade / Craft',
    state: 'MI',
    city: 'Detroit',
    salary: '$52,000 - $65,000 annually',
    salaryMin: 52000,
    salaryMax: 65000,
    jobType: 'Full-time',
    description: 'Assist licensed journeymen with duct fabrication, piping, and rooftop package installations.',
    requirements: ['Valid drivers license', 'Mechanical aptitude', 'Eagerness to learn through apprenticeship program'],
    contactEmail: 'apprentice@metroairdynamics.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-09T08:30:00Z',
  },
  {
    id: 'demo-job-27',
    title: 'Summer B2B Marketing Strategy Intern',
    company: 'Ascend Growth Agency',
    category: 'Marketing / PR / Advertising',
    state: 'NC',
    city: 'Raleigh',
    salary: '$20 / hr (Paid Internship)',
    salaryMin: 35000,
    salaryMax: 42000,
    jobType: 'Internship',
    description: 'Support content creation, competitor research, and social media scheduling for mid-Atlantic business clients.',
    requirements: ['Current student or recent graduate in Marketing or Communications', 'Excellent written English'],
    contactEmail: 'internships@ascendgrowth.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-09T10:00:00Z',
  },
  {
    id: 'demo-job-28',
    title: 'Senior Property Manager (Class A Commercial)',
    company: 'Highline Asset Management',
    category: 'Real Estate & Property Management',
    state: 'TX',
    city: 'San Antonio',
    salary: '$85,000 - $110,000 annually',
    salaryMin: 85000,
    salaryMax: 110000,
    jobType: 'Full-time',
    description: 'Manage lease compliance, capital improvement budgets, and vendor maintenance contracts for 450,000 sq ft of commercial office space.',
    requirements: ['CPM or RPA designation preferred', '4+ years commercial property management', 'Yardi software fluency'],
    contactEmail: 'properties@highlineasset.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-09T11:45:00Z',
  },
  {
    id: 'demo-job-29',
    title: 'Cloud DevOps & Site Reliability Engineer',
    company: 'Nimbus Infrastructure Co',
    category: 'Technology (SaaS)',
    state: 'WA',
    city: 'Seattle',
    salary: '$145,000 - $185,000 annually',
    salaryMin: 145000,
    salaryMax: 185000,
    jobType: 'Full-time',
    description: 'Maintain CI/CD deployment pipelines, manage AWS/GCP Kubernetes clusters, and monitor 99.99% system uptime.',
    requirements: ['AWS Certified Solutions Architect or DevOps Pro', 'Docker, Terraform, and Kubernetes mastery', 'On-call rotation availability'],
    contactEmail: 'devops@nimbusinfra.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-09T14:15:00Z',
    featured: true,
  },
  {
    id: 'demo-job-30',
    title: 'Inside Sales Development Representative (SDR)',
    company: 'LeadForge Technologies',
    category: 'B2B Sales',
    state: 'CO',
    city: 'Denver',
    salary: '$60,000 base + $25,000 Commission OTE',
    salaryMin: 60000,
    salaryMax: 85000,
    jobType: 'Full-time',
    description: 'Prospect outbound leads, execute phone and email cadences, and schedule qualified discovery demos for Account Executives.',
    requirements: ['1+ years SDR or outbound sales', 'Coachability and resilience', 'Experience with Salesforce or HubSpot'],
    contactEmail: 'careers@leadforge.demo',
    status: 'approved',
    isDemo: true,
    createdAt: '2026-10-09T16:00:00Z',
  },
]
