import { Menu } from '../lib/rbac/types'

/**
 * Complete Master Menu Catalog for OAL / B4B Financial Platform
 * 
 * Contains all menus across all portals:
 * - Admin: 16
 * - Biz Pro: 14 base + 6 leader menus (Rank 4+)
 * - Client: 8
 * - Affiliate: 7
 * - Employer: 7
 * - Job Seeker: 6
 * - Shared: 4 (eBOX, Messages, Profile, Settings)
 */
export const MENU_CATALOG: Menu[] = [
  // ==========================================
  // 1. ADMIN PORTAL MENUS (16)
  // ==========================================
  {
    id: 'admin-overview',
    label: 'Overview Dashboard',
    icon: 'LayoutDashboard',
    route: '/portal/admin/dashboard',
    module: 'Dashboard',
    group: 'Admin Operations',
    order: 1,
    isCore: true,
    description: 'Executive KPI metrics, volume trends and operations cockpit.',
  },
  {
    id: 'admin-bizpro',
    label: 'B4B Coach Management',
    icon: 'Users',
    route: '/portal/admin/bizpro',
    module: 'Leads and Clients',
    group: 'Network Management',
    order: 2,
    isCore: false,
    badge: '148 Active',
    badgeVariant: 'primary',
    description: 'Broker roster, licensing compliance, and downline hierarchy.',
  },
  {
    id: 'admin-bulletin',
    label: 'Bulletin CMS',
    icon: 'Megaphone',
    route: '/portal/admin/bulletin',
    module: 'Content',
    group: 'Content & Communications',
    order: 2.5,
    isCore: false,
    description: 'Author, edit, pin, and manage executive communications for the network.',
  },
  {
    id: 'admin-rank-rules',
    label: 'Rank & Promotion Rules',
    icon: 'Trophy',
    route: '/portal/admin/rank-rules',
    module: 'Commission and Rank',
    group: 'Compensation & Rules',
    order: 3,
    isCore: false,
    description: 'Configure 9-tier rank requirements, personal volume thresholds and perks.',
  },
  {
    id: 'admin-commission-maker',
    label: 'Commission Maker',
    icon: 'Sliders',
    route: '/portal/admin/commission-maker',
    module: 'Commission and Rank',
    group: 'Compensation & Rules',
    order: 4,
    isCore: false,
    badge: 'Rule Builder',
    badgeVariant: 'gold',
    description: 'Tier formulas, override splits, broker payouts, and ACH approval.',
  },
  {
    id: 'admin-territory',
    label: 'Territory Management',
    icon: 'MapPin',
    route: '/portal/admin/territory',
    module: 'Territory',
    group: 'Territory',
    order: 5,
    isCore: false,
    description: 'Regional boundaries, exclusivity grants, and dispatch rules.',
  },
  {
    id: 'admin-services',
    label: 'Service Inventory & Catalog',
    icon: 'ShoppingBag',
    route: '/portal/admin/services',
    module: 'Content',
    group: 'Catalog & Inventory',
    order: 6,
    isCore: false,
    badge: '16 Products',
    badgeVariant: 'navy',
    description: 'Underwriting matrix, commission percentages, and loan sizes.',
  },
  {
    id: 'admin-subscriptions',
    label: 'Subscriptions & Billing',
    icon: 'CreditCard',
    route: '/portal/admin/subscriptions',
    module: 'Billing',
    group: 'Finance & Billing',
    order: 7,
    isCore: false,
    description: '$25/mo membership billing, recurring subscriptions, and payment gateways.',
  },
  {
    id: 'admin-leads',
    label: 'All Leads Database',
    icon: 'Target',
    route: '/portal/admin/leads',
    module: 'Leads and Clients',
    group: 'Network Management',
    order: 8,
    isCore: false,
    description: 'Master multi-portal CRM lead funnel and underwriter assignment.',
  },
  {
    id: 'admin-clients',
    label: 'Clients Directory',
    icon: 'Building2',
    route: '/portal/admin/clients',
    module: 'Leads and Clients',
    group: 'Network Management',
    order: 9,
    isCore: false,
    description: 'Portfolio company directory, funded debt facilities, and health scores.',
  },
  {
    id: 'admin-scoreboard',
    label: 'Scoreboard Settings',
    icon: 'TrendingUp',
    route: '/portal/admin/scoreboard-settings',
    module: 'System',
    group: 'System Configuration',
    order: 10,
    isCore: false,
    description: 'Configure national bulletin race formulas and monthly bonuses.',
  },
  {
    id: 'admin-jobs',
    label: 'Jobs Moderation',
    icon: 'Briefcase',
    route: '/portal/admin/jobs-moderation',
    module: 'Jobs',
    group: 'Job Board',
    order: 11,
    isCore: false,
    badge: '5 Pending',
    badgeVariant: 'amber',
    description: 'Review and approve employer job postings and compliance.',
  },
  {
    id: 'admin-affiliates',
    label: 'Affiliates Management',
    icon: 'Share2',
    route: '/portal/admin/affiliates',
    module: 'Leads and Clients',
    group: 'Network Management',
    order: 12,
    isCore: false,
    description: 'Partner links, clicks tracking, conversion payouts, and media kit.',
  },
  {
    id: 'admin-cms',
    label: 'Website Content (CMS)',
    icon: 'Globe',
    route: '/portal/admin/cms',
    module: 'Content',
    group: 'Catalog & Inventory',
    order: 13,
    isCore: false,
    description: 'Manage marketing landing copy, solution pages, and press items.',
  },
  {
    id: 'admin-training',
    label: 'Training Content',
    icon: 'GraduationCap',
    route: '/portal/admin/training-cms',
    module: 'Content',
    group: 'Catalog & Inventory',
    order: 14,
    isCore: false,
    description: 'CCDA masterclass videos, underwriter scripts, and exam quizzes.',
  },
  {
    id: 'admin-roles-permissions',
    label: 'Roles & Permissions',
    icon: 'ShieldCheck',
    route: '/portal/admin/roles-permissions',
    module: 'System',
    group: 'System Configuration',
    order: 15,
    isCore: true, // MUST NEVER BE REMOVED FOR ADMIN
    badge: 'Matrix',
    badgeVariant: 'purple',
    description: 'Full RBAC dynamic security matrix and role configurator.',
  },
  {
    id: 'admin-reports',
    label: 'Reports & Analytics',
    icon: 'BarChart3',
    route: '/portal/admin/reports',
    module: 'Reports',
    group: 'Reports & Analytics',
    order: 16,
    isCore: false,
    description: 'Corporate portfolio volume reports, underwriter velocity, and CSV exports.',
  },

  // ==========================================
  // 2. BIZ PRO CORE MENUS (15)
  // ==========================================
  {
    id: 'bizpro-bulletin',
    label: 'B4B Bulletin',
    icon: 'Megaphone',
    route: '/portal/bizpro/bulletin',
    module: 'Dashboard',
    group: 'Biz Pro Core',
    order: 100,
    isCore: true,
    badge: 'Live',
    badgeVariant: 'primary',
    description: 'Executive national announcements, commercial program rollouts, and updates feed.',
  },
  {
    id: 'bizpro-dashboard',
    label: 'Sales Dashboard',
    icon: 'LayoutDashboard',
    route: '/portal/bizpro/dashboard',
    module: 'Dashboard',
    group: 'Biz Pro Core',
    order: 101,
    isCore: true,
    description: 'KPI sparklines, revenue chart, lead funnel, and next rank progress ring.',
  },
  {
    id: 'bizpro-leads',
    label: 'Leads CRM',
    icon: 'Target',
    route: '/portal/bizpro/leads',
    module: 'Leads and Clients',
    group: 'Biz Pro Core',
    order: 102,
    isCore: false,
    badge: '24 Active',
    badgeVariant: 'primary',
    description: 'Dual Kanban board and table view with stage transition actions.',
  },
  {
    id: 'bizpro-clients',
    label: 'Clients Directory',
    icon: 'Building2',
    route: '/portal/bizpro/clients',
    module: 'Leads and Clients',
    group: 'Biz Pro Core',
    order: 103,
    isCore: false,
    description: 'Deep client files, active debt facilities, and documents vault.',
  },
  {
    id: 'bizpro-communication',
    label: 'Communication Inbox',
    icon: 'MessageSquare',
    route: '/portal/bizpro/communication',
    module: 'Shared',
    group: 'Biz Pro Core',
    order: 104,
    isCore: false,
    badge: '3 Unread',
    badgeVariant: 'amber',
    description: 'Direct messaging channels with Underwriting Pod and clients.',
  },
  {
    id: 'bizpro-marketing',
    label: 'AI Marketing Hub',
    icon: 'Sparkles',
    route: '/portal/bizpro/marketing',
    module: 'Content',
    group: 'Biz Pro Core',
    order: 105,
    isCore: false,
    description: 'AI prompt marketing copy generator with automatic sponsor code attribution.',
  },
  {
    id: 'bizpro-services',
    label: 'Service Catalog',
    icon: 'ShoppingBag',
    route: '/portal/bizpro/catalog',
    module: 'Content',
    group: 'Biz Pro Core',
    order: 106,
    isCore: false,
    badge: '16 Services',
    badgeVariant: 'navy',
    description: '16 commercial debt & credit products with broker commission splits.',
  },
  {
    id: 'bizpro-commissions',
    label: 'My Commissions',
    icon: 'Wallet',
    route: '/portal/bizpro/commissions',
    module: 'Commission and Rank',
    group: 'Biz Pro Core',
    order: 107,
    isCore: false,
    badge: '$14.2k',
    badgeVariant: 'gold',
    description: 'Itemized commission statements, direct ACH deposits, and PDF export.',
  },
  {
    id: 'bizpro-rank',
    label: 'My Rank & Promotion',
    icon: 'Trophy',
    route: '/portal/bizpro/rank',
    module: 'Commission and Rank',
    group: 'Biz Pro Core',
    order: 108,
    isCore: false,
    description: '9-tier career roadmap with next rank requirements checklist.',
  },
  {
    id: 'bizpro-scoreboard',
    label: 'Bulletin Scoreboard',
    icon: 'TrendingUp',
    route: '/portal/bizpro/scoreboard',
    module: 'System',
    group: 'Biz Pro Core',
    order: 109,
    isCore: false,
    description: 'National and regional producer scoreboard and promotions bulletin.',
  },
  {
    id: 'bizpro-training',
    label: 'Training & Videos',
    icon: 'GraduationCap',
    route: '/portal/bizpro/training',
    module: 'Content',
    group: 'Biz Pro Core',
    order: 110,
    isCore: false,
    description: 'B4B Coach Academy certification masterclasses and underwriting scripts.',
  },
  {
    id: 'bizpro-territory',
    label: 'My Territory',
    icon: 'MapPin',
    route: '/portal/bizpro/territory',
    module: 'Territory',
    group: 'Biz Pro Core',
    order: 111,
    isCore: false,
    description: 'Exclusivity rights mapping, county allocations, and B2B market volume.',
  },
  {
    id: 'bizpro-branding',
    label: 'White-label Branding',
    icon: 'Palette',
    route: '/portal/bizpro/branding',
    module: 'Content',
    group: 'Biz Pro Core',
    order: 112,
    isCore: false,
    description: 'Custom broker subdomain, company logo, and client portal theme.',
  },
  {
    id: 'bizpro-support',
    label: 'VIP Support Desk',
    icon: 'HelpCircle',
    route: '/portal/bizpro/support',
    module: 'System',
    group: 'Biz Pro Core',
    order: 113,
    isCore: false,
    description: 'Priority underwriting hotline and fast-track ticket support.',
  },
  {
    id: 'bizpro-subscription',
    label: 'Profile & Subscription',
    icon: 'CreditCard',
    route: '/portal/bizpro/subscription',
    module: 'Billing',
    group: 'Biz Pro Core',
    order: 114,
    isCore: true,
    badge: '$25/mo',
    badgeVariant: 'emerald',
    description: '$25/month starter platform membership card, billing receipts, and profile.',
  },

  // ==========================================
  // 3. BIZ PRO LEADER EXTRA MENUS (6, Rank 4+)
  // ==========================================
  {
    id: 'bizpro-team',
    label: 'My Team',
    icon: 'Users',
    route: '/portal/bizpro/team',
    module: 'Leads and Clients',
    group: 'Biz Pro Leadership (Rank 4+)',
    order: 115,
    isCore: false,
    isLeaderOnly: true,
    minRank: 4,
    badge: '5 Direct',
    badgeVariant: 'purple',
    description: 'Hierarchical Org-Tree view of downline members, ranks, and overrides.',
  },
  {
    id: 'bizpro-team-commissions',
    label: 'Team Commission',
    icon: 'Percent',
    route: '/portal/bizpro/team-commissions',
    module: 'Commission and Rank',
    group: 'Biz Pro Leadership (Rank 4+)',
    order: 116,
    isCore: false,
    isLeaderOnly: true,
    minRank: 4,
    badge: '$9.7k',
    badgeVariant: 'gold',
    description: 'Multi-tier volume overrides ledger and passive income simulator.',
  },
  {
    id: 'bizpro-recruit',
    label: 'Recruit',
    icon: 'UserPlus',
    route: '/portal/bizpro/recruit',
    module: 'Leads and Clients',
    group: 'Biz Pro Leadership (Rank 4+)',
    order: 117,
    isCore: false,
    isLeaderOnly: true,
    minRank: 4,
    badge: 'Invite',
    badgeVariant: 'emerald',
    description: 'Candidate invitation email form with sponsor code attribution and QR code.',
  },
  {
    id: 'bizpro-team-scoreboard',
    label: 'Team Scoreboard',
    icon: 'Award',
    route: '/portal/bizpro/team-scoreboard',
    module: 'System',
    group: 'Biz Pro Leadership (Rank 4+)',
    order: 118,
    isCore: false,
    isLeaderOnly: true,
    minRank: 4,
    description: 'Internal downline producer race and monthly incentive rankings.',
  },
  {
    id: 'bizpro-territory-assignment',
    label: 'Territory Assignment',
    icon: 'Globe',
    route: '/portal/bizpro/territory-assignment',
    module: 'Territory',
    group: 'Biz Pro Leadership (Rank 4+)',
    order: 119,
    isCore: false,
    isLeaderOnly: true,
    minRank: 4,
    description: 'Dispatch counties and municipal zip codes across junior advisors.',
  },
  {
    id: 'bizpro-team-reports',
    label: 'Team Reports',
    icon: 'BarChart3',
    route: '/portal/bizpro/team-reports',
    module: 'Reports',
    group: 'Biz Pro Leadership (Rank 4+)',
    order: 120,
    isCore: false,
    isLeaderOnly: true,
    minRank: 4,
    description: 'Downline production volume analytics, producer scorecards, and CSV export.',
  },

  // ==========================================
  // 4. CLIENT PORTAL MENUS (8)
  // ==========================================
  {
    id: 'client-dashboard',
    label: 'Client Dashboard',
    icon: 'LayoutDashboard',
    route: '/portal/dashboard',
    module: 'Dashboard',
    group: 'Client Portal',
    order: 201,
    isCore: true,
    description: 'Funding trajectory, credit facility balances, and advisor contact card.',
  },
  {
    id: 'client-orders',
    label: 'My Services & Orders',
    icon: 'ShoppingBag',
    route: '/portal/client/orders',
    module: 'Content',
    group: 'Client Portal',
    order: 202,
    isCore: false,
    badge: '3 Active',
    badgeVariant: 'primary',
    description: 'Enrolled debt restructuring, POS processing, and corporate credit builds.',
  },
  {
    id: 'client-funding',
    label: 'Funding & Business Plan',
    icon: 'TrendingUp',
    route: '/portal/client/funding-status',
    module: 'Billing',
    group: 'Client Portal',
    order: 203,
    isCore: false,
    badge: 'Under Review',
    badgeVariant: 'amber',
    description: 'Underwriter review milestone tracker and SBA package checklist.',
  },
  {
    id: 'client-documents',
    label: 'Documents Vault',
    icon: 'FileCheck2',
    route: '/portal/client/documents',
    module: 'Shared',
    group: 'Client Portal',
    order: 204,
    isCore: false,
    description: 'Tax returns, bank statements, P&L models, and executed term sheets.',
  },
  {
    id: 'client-messages',
    label: 'Messages with Coach',
    icon: 'MessageSquare',
    route: '/portal/client/messages',
    module: 'Shared',
    group: 'Client Portal',
    order: 205,
    isCore: false,
    badge: '1 New',
    badgeVariant: 'emerald',
    description: 'Direct advisory chat channel with assigned Fractional CFO and coach.',
  },
  {
    id: 'client-invoices',
    label: 'Payments & Invoices',
    icon: 'CreditCard',
    route: '/portal/client/invoices',
    module: 'Billing',
    group: 'Client Portal',
    order: 206,
    isCore: false,
    badge: '1 Due',
    badgeVariant: 'gold',
    description: 'Review invoice schedules, facility interest statements, and receipts.',
  },
  {
    id: 'client-book-coach',
    label: 'Book a Coach',
    icon: 'Zap',
    route: '/portal/client/book-coach',
    module: 'Content',
    group: 'Client Portal',
    order: 207,
    isCore: false,
    description: 'Schedule 1-on-1 strategy sessions with commercial credit advisors.',
  },
  {
    id: 'client-support',
    label: 'Help & Support',
    icon: 'HelpCircle',
    route: '/portal/client/support',
    module: 'System',
    group: 'Client Portal',
    order: 208,
    isCore: false,
    description: 'Helpdesk ticket system and commercial underwriting FAQs.',
  },

  // ==========================================
  // 5. AFFILIATE / PARTNER PORTAL MENUS (7)
  // ==========================================
  {
    id: 'affiliate-dashboard',
    label: 'Partner Dashboard',
    icon: 'LayoutDashboard',
    route: '/portal/affiliate/dashboard',
    module: 'Dashboard',
    group: 'Affiliate Portal',
    order: 301,
    isCore: true,
    description: 'Clicks, referred leads, funded volume, and lifetime earnings.',
  },
  {
    id: 'affiliate-links',
    label: 'My Unique Links',
    icon: 'Share2',
    route: '/portal/affiliate/links',
    module: 'Leads and Clients',
    group: 'Affiliate Portal',
    order: 302,
    isCore: false,
    badge: '6 Links',
    badgeVariant: 'purple',
    description: 'Copy referral links, custom UTM tags, and dynamic SVG QR codes.',
  },
  {
    id: 'affiliate-submit-lead',
    label: 'Submit Direct Lead',
    icon: 'UserPlus',
    route: '/portal/affiliate/submit-lead',
    module: 'Leads and Clients',
    group: 'Affiliate Portal',
    order: 303,
    isCore: false,
    badge: 'Fast Track',
    badgeVariant: 'emerald',
    description: 'Submit client prospect directly to commercial underwriters.',
  },
  {
    id: 'affiliate-referrals',
    label: 'Referral Pipeline',
    icon: 'Target',
    route: '/portal/affiliate/referrals',
    module: 'Leads and Clients',
    group: 'Affiliate Portal',
    order: 304,
    isCore: false,
    badge: '38 Funded',
    badgeVariant: 'primary',
    description: 'Table of referred clients, loan amounts, and funding stages.',
  },
  {
    id: 'affiliate-commissions',
    label: 'Commissions & Payouts',
    icon: 'Wallet',
    route: '/portal/affiliate/commissions',
    module: 'Commission and Rank',
    group: 'Affiliate Portal',
    order: 305,
    isCore: false,
    badge: '$4.3k',
    badgeVariant: 'gold',
    description: 'Payout schedule, direct deposit ACH setup, and statements.',
  },
  {
    id: 'affiliate-marketing',
    label: 'Marketing Materials',
    icon: 'Sparkles',
    route: '/portal/affiliate/marketing',
    module: 'Content',
    group: 'Affiliate Portal',
    order: 306,
    isCore: false,
    badge: '24 Assets',
    badgeVariant: 'navy',
    description: 'Downloadable banner kits, PDF one-pagers, and social copy.',
  },
  {
    id: 'affiliate-profile',
    label: 'Partner Profile',
    icon: 'ShieldCheck',
    route: '/portal/affiliate/profile',
    module: 'System',
    group: 'Affiliate Portal',
    order: 307,
    isCore: true,
    description: 'Affiliate tax W-9 info, banking routing, and profile settings.',
  },

  // ==========================================
  // 6. EMPLOYER PORTAL MENUS (7)
  // ==========================================
  {
    id: 'employer-dashboard',
    label: 'Employer Dashboard',
    icon: 'LayoutDashboard',
    route: '/portal/employer/dashboard',
    module: 'Dashboard',
    group: 'Employer Portal',
    order: 401,
    isCore: true,
    description: 'Overview of active jobs, applicant counts, and hiring velocity.',
  },
  {
    id: 'employer-post-job',
    label: 'Post a Job',
    icon: 'PlusCircle',
    route: '/portal/employer/post-job',
    module: 'Jobs',
    group: 'Employer Portal',
    order: 402,
    isCore: false,
    badge: 'Hire Fast',
    badgeVariant: 'emerald',
    description: 'Create and publish job listings to corporate career directory.',
  },
  {
    id: 'employer-jobs',
    label: 'My Posted Jobs',
    icon: 'Briefcase',
    route: '/portal/employer/jobs',
    module: 'Jobs',
    group: 'Employer Portal',
    order: 403,
    isCore: false,
    badge: '4 Active',
    badgeVariant: 'primary',
    description: 'Manage active, paused, and archived recruitment listings.',
  },
  {
    id: 'employer-applicants',
    label: 'Applicants Kanban',
    icon: 'Users',
    route: '/portal/employer/applicants',
    module: 'Jobs',
    group: 'Employer Portal',
    order: 404,
    isCore: false,
    badge: '18 Candidates',
    badgeVariant: 'amber',
    description: 'Candidate screening pipeline from Applied to Interview and Offer.',
  },
  {
    id: 'employer-company',
    label: 'Company Profile',
    icon: 'Building2',
    route: '/portal/employer/profile',
    module: 'System',
    group: 'Employer Portal',
    order: 405,
    isCore: true,
    description: 'Company culture, branding logo, benefits package, and website.',
  },
  {
    id: 'employer-billing',
    label: 'Billing & Plan',
    icon: 'CreditCard',
    route: '/portal/employer/billing',
    module: 'Billing',
    group: 'Employer Portal',
    order: 406,
    isCore: false,
    description: 'Job board subscription packages, featured boosts, and invoices.',
  },
  {
    id: 'employer-messages',
    label: 'Candidate Messages',
    icon: 'MessageSquare',
    route: '/portal/employer/messages',
    module: 'Shared',
    group: 'Employer Portal',
    order: 407,
    isCore: false,
    badge: '2 New',
    badgeVariant: 'emerald',
    description: 'Direct messaging channel with applied candidates.',
  },

  // ==========================================
  // 7. JOB SEEKER PORTAL MENUS (6)
  // ==========================================
  {
    id: 'seeker-dashboard',
    label: 'Seeker Dashboard',
    icon: 'LayoutDashboard',
    route: '/portal/seeker/dashboard',
    module: 'Dashboard',
    group: 'Job Seeker Portal',
    order: 501,
    isCore: true,
    description: 'Application statuses, saved job alerts, and interview invitations.',
  },
  {
    id: 'seeker-search',
    label: 'Search Jobs & Gigs',
    icon: 'Search',
    route: '/portal/seeker/search',
    module: 'Jobs',
    group: 'Job Seeker Portal',
    order: 502,
    isCore: false,
    description: 'Browse commercial finance, advisory, and fintech positions.',
  },
  {
    id: 'seeker-saved',
    label: 'Saved Jobs',
    icon: 'Heart',
    route: '/portal/seeker/saved',
    module: 'Jobs',
    group: 'Job Seeker Portal',
    order: 503,
    isCore: false,
    badge: '3 Bookmarks',
    badgeVariant: 'purple',
    description: 'Bookmarked job openings for quick application.',
  },
  {
    id: 'seeker-applications',
    label: 'My Applications',
    icon: 'Award',
    route: '/portal/seeker/applications',
    module: 'Jobs',
    group: 'Job Seeker Portal',
    order: 504,
    isCore: false,
    badge: '2 Active',
    badgeVariant: 'emerald',
    description: 'Track submitted resumes, employer reviews, and interview schedules.',
  },
  {
    id: 'seeker-profile',
    label: 'Profile & Resume',
    icon: 'FileText',
    route: '/portal/seeker/profile',
    module: 'System',
    group: 'Job Seeker Portal',
    order: 505,
    isCore: true,
    description: 'Digital CV, LinkedIn link, education credentials, and career bio.',
  },
  {
    id: 'seeker-alerts',
    label: 'Job Alerts',
    icon: 'Bell',
    route: '/portal/seeker/alerts',
    module: 'Jobs',
    group: 'Job Seeker Portal',
    order: 506,
    isCore: false,
    description: 'Email and notification preferences for newly posted positions.',
  },

  // ==========================================
  // 8. SHARED MENUS (4)
  // ==========================================
  {
    id: 'shared-ebox',
    label: 'eBOX Vault',
    icon: 'FolderArchive',
    route: '/portal/ebox',
    module: 'Shared',
    group: 'Shared Platform',
    order: 601,
    isCore: false,
    badge: 'Vault',
    badgeVariant: 'emerald',
    description: 'Encrypted document locker and financial underwriting vault.',
  },
  {
    id: 'shared-messages',
    label: 'Messages Inbox',
    icon: 'MessageSquare',
    route: '/portal/messages',
    module: 'Shared',
    group: 'Shared Platform',
    order: 602,
    isCore: false,
    description: 'Platform-wide encrypted chat and communication threads.',
  },
  {
    id: 'shared-profile',
    label: 'Profile & Account',
    icon: 'User',
    route: '/portal/profile',
    module: 'Shared',
    group: 'Shared Platform',
    order: 603,
    isCore: true,
    description: 'Account security, two-factor authentication, and contact details.',
  },
  {
    id: 'shared-settings',
    label: 'Portal Settings',
    icon: 'Settings',
    route: '/portal/settings',
    module: 'Shared',
    group: 'Shared Platform',
    order: 604,
    isCore: true,
    description: 'Theme preferences, sound notifications, and session security.',
  },
]

export const MENU_MODULES = [
  'Dashboard',
  'Leads and Clients',
  'Commission and Rank',
  'Territory',
  'Jobs',
  'Billing',
  'Content',
  'Reports',
  'System',
  'Shared',
] as const

export const MODULE_ORDER = MENU_MODULES

export const MENU_MAP: Record<string, Menu> = MENU_CATALOG.reduce((acc, item) => {
  acc[item.id] = item
  return acc
}, {} as Record<string, Menu>)
